import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, realpath, rm, rmdir, stat, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";

import {
  CheckpointSchema,
  ForkSchema,
  type Checkpoint,
  type Fork,
  type ModelSelection,
  type SessionEventDraft,
} from "@novus/contracts";

const run = promisify(execFile);

/**
 * Where a repository's forks live, given the repository.
 *
 * A sibling of the checkout, never a child of it. A worktree inside the
 * repository would appear in the parent's `git status`, in `list_directory`,
 * and in every search the parent agent runs — so the two attempts would be
 * reading each other's work through the one directory that is supposed to
 * separate them. One directory per repository keeps two projects' forks from
 * mixing, and `scripts/fleet.sh` puts its own worktrees in the same place for
 * the same reason.
 */
const defaultForkRoot = (repositoryRoot: string): string =>
  join(dirname(repositoryRoot), ".novus-forks", basename(repositoryRoot));

/**
 * The first development port a fork may be given.
 *
 * Above the host worker (4319) and both Vite servers (5273, 5274) so a fork's
 * dev server never lands on the port the human is already watching Novus on.
 */
const DEFAULT_PORT_BASE = 4400;
const DEFAULT_PORTS_PER_FORK = 2;
const PORT_SCAN_LIMIT = 512;

/** Git and filesystem calls are bounded: a fork must never hang the worker. */
const GIT_TIMEOUT_MS = 15_000;
const GIT_MAX_BUFFER = 64 * 1024 * 1024;

const isOutside = (root: string, target: string): boolean => {
  const fromRoot = relative(root, target);

  return fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot);
};

/**
 * Identifiers that become a path segment and a branch name.
 *
 * A run id is generated by Novus today, but a fork can also be asked for by a
 * client, and this is the point where "the fork's directory is derived from its
 * id" would otherwise become "the caller chooses any directory on the disk".
 * `../../etc` is a valid string and an invalid path segment, so the check is
 * on the character set rather than on what the resulting path looks like —
 * there is nothing to normalise away if nothing unusual was ever accepted.
 */
const SAFE_IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

/**
 * Neither directory may contain the other.
 *
 * A fork root inside the repository would put every attempt's files in front
 * of the parent's own tools — `git status`, `list_directory`, every search.
 * A repository inside the fork root would mean tearing forks down could take
 * the human's checkout with it. Neither overlap "escapes" in the `..` sense,
 * which is why this is a containment check and not a path check.
 */
const assertDisjoint = (repositoryRoot: string, forkRoot: string): void => {
  if (!isOutside(repositoryRoot, forkRoot)) {
    throw new Error(
      `Fork worktrees must live outside the selected repository: ${forkRoot} is inside ${repositoryRoot}`,
    );
  }

  if (!isOutside(forkRoot, repositoryRoot)) {
    throw new Error(
      `The selected repository is inside the fork root: ${repositoryRoot} is inside ${forkRoot}`,
    );
  }
};

const assertSafeIdentifier = (value: string, what: string): void => {
  if (!SAFE_IDENTIFIER.test(value) || value.includes("..")) {
    throw new Error(
      `${what} must be letters, digits, dot, dash, or underscore: refused ${JSON.stringify(value)}`,
    );
  }
};

const isPortFree = (port: number): Promise<boolean> =>
  new Promise((settle) => {
    const server = createServer();

    server.once("error", () => settle(false));
    server.once("listening", () => {
      server.close(() => settle(true));
    });
    // Bound on every interface rather than loopback, which is not what the
    // fork will use but is the only way to learn the truth: BSD SO_REUSEADDR
    // lets a 127.0.0.1 bind succeed over a live 0.0.0.0 listener, so probing
    // loopback handed out ports that were already taken.
    server.listen(port, "0.0.0.0");
  });

export type CheckpointInput = {
  sessionId: string;
  parentRunId: string;
  /** The parent's event sequence this checkpoint covers. */
  parentSequence: number;
  agentState: string;
  goal: string;
  model: ModelSelection;
  toolPolicy: { allowWrites: boolean; allowCommands: boolean };
  contextManifest?: readonly string[] | undefined;
  constraints?: readonly string[] | undefined;
  budget?:
    | { remainingModelCalls: number | null; remainingTokens: number | null }
    | undefined;
};

export type ForkInput = {
  /** The fork's unique run id. Its worktree and branch are derived from it. */
  runId: string;
  label: string;
};

/**
 * A live fork: the record that goes in the log, plus what the host needs to
 * actually run in it.
 */
export type ForkHandle = {
  fork: Fork;
  worktreePath: string;
  branch: string;
  /**
   * The fork's process namespace, in the only form V1 can honestly provide.
   *
   * There are no containers in V1 and macOS has no cheap namespace primitive,
   * so a fork's separation from its sibling is: a different working directory,
   * different development ports, and an environment that names this fork
   * rather than inheriting the parent's. Anything spawned for this fork is
   * spawned with these, and nothing spawned for one fork can be handed the
   * other's repository path by accident.
   *
   * What is NOT separate, because `git worktree` shares one repository: the
   * object database, every ref, the stash, and the hooks directory. A fork
   * running `git update-ref` can move the parent's branch. A fork running
   * `git worktree remove --force` can delete a live sibling. A stash pushed in
   * one appears in all of them, and a hook written from one runs on the
   * parent's next commit. An audit demonstrated each of these.
   *
   * So "two attempts run without interfering" is true of the working tree and
   * not of the repository. That is acceptable only because reaching any of it
   * requires `run_command`, which is `dangerous`, denied by default, and
   * separately opted into — a fork whose tool policy allows commands can reach
   * its parent, and that is the boundary as it actually stands. Real isolation
   * needs a separate object store per attempt, which is a clone rather than a
   * worktree, and is the change to make if forks are ever given commands by
   * default.
   */
  environment: Record<string, string>;
};

/**
 * Creates and destroys the isolated checkouts that forked attempts run in.
 *
 * The unit of isolation is a Git worktree, because it is the only mechanism
 * here that is native, inspectable, and cheap: a second checkout of the same
 * object database, with its own working directory, index, and branch. Copying
 * the repository would be none of those things, and running two attempts in
 * one directory is what this class exists to make impossible.
 *
 * Every fork this manager makes is also every fork it will remove. A worktree
 * it did not create is not its business, and a creation that fails part-way is
 * unmade before the error is raised — `scripts/fleet.sh` learned that a
 * half-made worktree is worse than no worktree, because it looks usable right
 * up until an agent is standing in it.
 */
export class WorktreeManager {
  private readonly repositoryPath: string;
  private readonly requestedForkRoot: string | undefined;
  private readonly portBase: number;
  private readonly portsPerFork: number;
  private readonly forks = new Map<string, ForkHandle>();
  private readonly reservedPorts = new Set<number>();
  private repositoryRoot: string | undefined;
  private forkRoot: string | undefined;

  constructor(
    repositoryPath: string,
    options: {
      forkRoot?: string | undefined;
      portBase?: number | undefined;
      portsPerFork?: number | undefined;
    } = {},
  ) {
    this.repositoryPath = repositoryPath;
    this.requestedForkRoot = options.forkRoot;
    this.portBase = options.portBase ?? DEFAULT_PORT_BASE;
    this.portsPerFork = options.portsPerFork ?? DEFAULT_PORTS_PER_FORK;
  }

  list(): ForkHandle[] {
    return [...this.forks.values()];
  }

  get(runId: string): ForkHandle | undefined {
    return this.forks.get(runId);
  }

  /**
   * Captures the state a fork can be started from.
   *
   * Reads the repository and writes nothing to it. That is not an efficiency
   * argument: checkpointing is something a human does *while* a run is going,
   * and a capture that staged files or wrote a stash would change the tree the
   * parent run is still working in.
   *
   * Untracked files are included, and getting there without breaking the rule
   * above took a third option. `git diff HEAD` cannot see them; `git add -N`
   * would show them by writing to the parent's index, which is the mutation
   * this refuses. So the capture builds a *temporary* index — GIT_INDEX_FILE
   * pointed at a scratch path — stages everything into that, and diffs it. The
   * parent's index is never opened for writing, and a file the agent created
   * still crosses into the fork. An agent creating a file is the ordinary case,
   * so a checkpoint that dropped it was wrong in the ordinary case.
   */
  async createCheckpoint(input: CheckpointInput): Promise<Checkpoint> {
    const repositoryRoot = await this.resolveRepositoryRoot();

    const revision = await this.git(repositoryRoot, ["rev-parse", "HEAD"])
      .then((stdout) => stdout.trim())
      .catch(() => "");

    if (revision.length === 0) {
      // Not a soft failure with a null revision, the way a receipt reports one.
      // A fork has to check something out, and there is nothing here to check
      // out — saying so now is better than a worktree add that fails later
      // with Git's own wording.
      // Actionable, because the fix is two commands and the failure otherwise
      // reads like the feature is broken. A fork is a Git worktree cut from a
      // commit, so there has to be a commit.
      throw new Error(
        `Cannot fork ${repositoryRoot}: a fork is a Git worktree cut from a commit, and this directory has none yet. Run \`git init && git add -A && git commit -m "initial"\` in it, then try again.`,
      );
    }

    // Pinned before anything else reads it. Immutability rested entirely on the
    // reflog, so `git reflog expire --expire=now --all && git gc --prune=now`
    // in the parent made every outstanding checkpoint unforkable. A ref under
    // refs/novus/checkpoints keeps the base reachable for as long as the
    // checkpoint exists, and teardown removes it.
    const id = crypto.randomUUID();

    await this.git(repositoryRoot, [
      "update-ref",
      `refs/novus/checkpoints/${id}`,
      revision,
    ]).catch(() => "");

    // A scratch index, so staging everything does not touch the parent's.
    // --binary so a tree with changed binary files reproduces rather than
    // applying cleanly and quietly dropping them.
    const scratchIndex = join(
      await mkdtemp(join(tmpdir(), "novus-checkpoint-")),
      "index",
    );

    let patch = "";

    try {
      await this.git(repositoryRoot, ["add", "-A", "--", "."], {
        GIT_INDEX_FILE: scratchIndex,
      });
      patch = await this.git(
        repositoryRoot,
        ["diff", "--binary", "--cached", revision],
        { GIT_INDEX_FILE: scratchIndex },
      );
    } catch {
      patch = "";
    } finally {
      await rm(dirname(scratchIndex), { recursive: true, force: true });
    }

    return CheckpointSchema.parse({
      id,
      sessionId: input.sessionId,
      parentRunId: input.parentRunId,
      parentSequence: input.parentSequence,
      base: {
        revision,
        patch: patch.length > 0 ? patch : null,
      },
      agentState: input.agentState,
      contextManifest: [...(input.contextManifest ?? [])],
      goal: input.goal,
      constraints: [...(input.constraints ?? [])],
      model: input.model,
      toolPolicy: input.toolPolicy,
      budget: input.budget ?? {
        remainingModelCalls: null,
        remainingTokens: null,
      },
      createdAt: new Date().toISOString(),
    });
  }

  /**
   * Materialises a checkpoint as its own checkout on its own branch.
   *
   * Ordered so that the cheap refusals happen before anything exists on disk:
   * a bad identifier, a fork root that overlaps the repository, or a directory
   * already in the way all fail with nothing to undo. Only once the ports are
   * reserved and the path is proven to be inside the fork root does Git get
   * asked to create anything — and from that line on, every failure path runs
   * the same teardown the caller would get from `removeFork`.
   */
  async createFork(checkpoint: Checkpoint, input: ForkInput): Promise<ForkHandle> {
    const validated = CheckpointSchema.parse(checkpoint);

    assertSafeIdentifier(input.runId, "A fork's run id");

    if (this.forks.has(input.runId)) {
      throw new Error(`Fork ${input.runId} already exists.`);
    }

    const repositoryRoot = await this.resolveRepositoryRoot();

    // The schema now refuses a ref name, but a well-formed object id can still
    // be one this repository has never heard of, or one a prune removed. Ask
    // before building anything, so the failure names the checkpoint rather than
    // arriving later in Git's words about a worktree.
    const resolved = await this.git(repositoryRoot, [
      "rev-parse",
      "--verify",
      "--quiet",
      `${validated.base.revision}^{commit}`,
    ]).catch(() => "");

    if (resolved.trim() !== validated.base.revision) {
      throw new Error(
        `Checkpoint ${validated.id} names ${validated.base.revision}, which is not a commit in ${repositoryRoot}. The base was pruned, or the checkpoint came from another repository.`,
      );
    }

    const forkRoot = await this.resolveForkRoot(repositoryRoot);
    const worktreePath = join(forkRoot, input.runId);
    const branch = `novus/fork/${input.runId}`;

    // The identifier check should already make this impossible. It is asserted
    // anyway because it is the actual invariant — "no fork escapes its root" —
    // and an invariant that is only enforced by a regular expression somewhere
    // else is one edit away from not being enforced at all.
    if (isOutside(forkRoot, worktreePath) || worktreePath === forkRoot) {
      throw new Error(
        `A fork's worktree must live under ${forkRoot}: refused ${worktreePath}`,
      );
    }

    if (await exists(worktreePath)) {
      throw new Error(`${worktreePath} already exists — refusing to fork onto it.`);
    }

    const devPorts = await this.reservePorts();

    try {
      await this.git(repositoryRoot, [
        "worktree",
        "add",
        "--no-track",
        "-b",
        branch,
        worktreePath,
        validated.base.revision,
      ]);
    } catch (error) {
      this.releasePorts(devPorts);
      // Tear down before rethrowing. A `worktree add` that fails partway leaves
      // Git holding a registration for a directory that may not exist, and
      // nothing prunes it — so the same run id could never be forked again, the
      // phantom stayed in `git worktree list`, and a dead branch accumulated in
      // the user's repository. Exactly what this class claims not to do.
      await this.destroyWorktree(repositoryRoot, worktreePath, branch);
      throw new Error(
        `Could not create a worktree for fork ${input.runId}: ${messageOf(error)}`,
      );
    }

    try {
      await this.applyBase(worktreePath, validated);

      const fork = ForkSchema.parse({
        runId: input.runId,
        sessionId: validated.sessionId,
        checkpointId: validated.id,
        parentRunId: validated.parentRunId,
        label: input.label,
        worktreePath: await realpath(worktreePath),
        branch,
        revision: validated.base.revision,
        devPorts,
        createdAt: new Date().toISOString(),
      });

      const handle: ForkHandle = {
        fork,
        worktreePath: fork.worktreePath,
        branch,
        environment: {
          NOVUS_REPO: fork.worktreePath,
          NOVUS_SESSION: fork.sessionId,
          NOVUS_RUN: fork.runId,
          NOVUS_FORK_PORTS: devPorts.join(","),
          PORT: String(devPorts[0]),
        },
      };

      this.forks.set(fork.runId, handle);

      return handle;
    } catch (error) {
      // The worktree exists and is wrong. Leaving it would hand the next
      // caller a checkout that is missing the parent's uncommitted work while
      // looking, from the outside, exactly like a good one.
      await this.destroyWorktree(repositoryRoot, worktreePath, branch);
      this.releasePorts(devPorts);

      throw new Error(
        `Could not start fork ${input.runId} from checkpoint ${validated.id}: ${messageOf(error)}`,
      );
    }
  }

  /**
   * Re-attaches a fork this repository already has on disk, from its durable
   * record in the log.
   *
   * This map is in-memory and empty in a fresh process, while `fork.created`
   * — and the worktree itself, under the fork root — both survive a restart.
   * Adoption is what turns the durable record back into an operable handle:
   * without it a restarted worker could still *list* an attempt from the log
   * but never diff it, apply it as a decision, or resume its paused run.
   *
   * Everything is re-verified rather than trusted. The record names a path,
   * and between then and now the human may have deleted it, pruned the
   * worktree, or pointed this worker at a different repository whose log
   * happens to mention the same directory. A fork that fails a check is
   * refused with the reason; the caller decides whether that is fatal — for
   * a session resume it is not, because the attempt's evidence is still in
   * the log even when its checkout is gone.
   */
  async adopt(fork: Fork): Promise<ForkHandle> {
    const validated = ForkSchema.parse(fork);

    assertSafeIdentifier(validated.runId, "A fork's run id");

    const existing = this.forks.get(validated.runId);

    if (existing) {
      return existing;
    }

    const repositoryRoot = await this.resolveRepositoryRoot();
    const forkRoot = await this.resolveForkRoot(repositoryRoot);

    let worktreePath: string;

    try {
      worktreePath = await realpath(validated.worktreePath);
    } catch {
      throw new Error(
        `Fork ${validated.runId}'s worktree is gone: ${validated.worktreePath} no longer exists on disk.`,
      );
    }

    // The same invariant createFork asserts — no fork escapes its root —
    // applied to a path that came from a log this process did not write.
    if (isOutside(forkRoot, worktreePath) || worktreePath === forkRoot) {
      throw new Error(
        `Fork ${validated.runId}'s recorded worktree is not under ${forkRoot}: refused ${worktreePath}`,
      );
    }

    // It has to be a worktree of *this* repository. A stale log entry from a
    // moved repository would otherwise hand out a handle whose diffs and
    // applies read from a tree that has nothing to do with this session.
    const commonDir = await this.git(worktreePath, [
      "rev-parse",
      "--path-format=absolute",
      "--git-common-dir",
    ])
      .then((stdout) => stdout.trim())
      .catch(() => "");
    const resolvedCommon = await realpath(commonDir).catch(() => "");
    const expectedCommon = await realpath(join(repositoryRoot, ".git")).catch(
      () => repositoryRoot,
    );

    if (resolvedCommon === "" || resolvedCommon !== expectedCommon) {
      throw new Error(
        `Fork ${validated.runId}'s directory at ${worktreePath} is not a worktree of ${repositoryRoot}.`,
      );
    }

    // Reserved, not probed. The record says these ports belong to this fork;
    // re-reserving them is what stops the next createFork from handing the
    // same ports to a new attempt. Whether something else on the machine took
    // them in the meantime is the same courtesy-probe caveat reservePorts
    // already documents.
    for (const port of validated.devPorts) {
      this.reservedPorts.add(port);
    }

    const handle: ForkHandle = {
      fork: { ...validated, worktreePath },
      worktreePath,
      branch: validated.branch,
      environment: {
        NOVUS_REPO: worktreePath,
        NOVUS_SESSION: validated.sessionId,
        NOVUS_RUN: validated.runId,
        NOVUS_FORK_PORTS: validated.devPorts.join(","),
        PORT: String(validated.devPorts[0]),
      },
    };

    this.forks.set(validated.runId, handle);

    return handle;
  }

  /**
   * Removes a fork's checkout and the branch that only it was using.
   *
   * The branch goes with the worktree deliberately. A fork's branch is not a
   * place work is kept — the selected attempt is applied as a patch, which is
   * Milestone 4's `apply selected patch` step — so leaving it behind would
   * accumulate one dead branch per attempt in the human's own repository.
   */
  async removeFork(runId: string): Promise<void> {
    const handle = this.forks.get(runId);

    if (!handle) {
      throw new Error(`No such fork: ${runId}`);
    }

    const repositoryRoot = await this.resolveRepositoryRoot();

    await this.destroyWorktree(repositoryRoot, handle.worktreePath, handle.branch);
    this.releasePorts(handle.fork.devPorts);
    this.forks.delete(runId);
  }

  /** Tears down every fork this manager still owns, reporting the first failure. */
  async removeAll(): Promise<void> {
    const failures: string[] = [];

    for (const runId of [...this.forks.keys()]) {
      try {
        await this.removeFork(runId);
      } catch (error) {
        failures.push(`${runId}: ${messageOf(error)}`);
      }
    }

    if (failures.length > 0) {
      throw new Error(`Some forks could not be removed — ${failures.join("; ")}`);
    }
  }

  /**
   * What a fork changed relative to the base it started from.
   *
   * The same temporary-index technique `createCheckpoint` uses to see the
   * parent's own uncommitted work, run here against the fork's worktree
   * instead — so a file the agent created but never `git add`ed is reported
   * exactly like one it edited, rather than silently missing because nothing
   * ever staged it.
   */
  async diffFork(
    runId: string,
  ): Promise<Array<{ path: string; status: "added" | "modified" | "deleted" }>> {
    const handle = this.forks.get(runId);

    if (!handle) {
      throw new Error(`No such fork: ${runId}`);
    }

    const scratchIndex = join(
      await mkdtemp(join(tmpdir(), "novus-fork-diff-")),
      "index",
    );

    try {
      await this.git(handle.worktreePath, ["add", "-A", "--", "."], {
        GIT_INDEX_FILE: scratchIndex,
      });

      const nameStatus = await this.git(
        handle.worktreePath,
        ["diff", "--name-status", "--cached", handle.fork.revision],
        { GIT_INDEX_FILE: scratchIndex },
      );

      return nameStatus
        .split("\n")
        .filter(Boolean)
        .map((line) => {
          const [code, ...rest] = line.split("\t");
          // A rename ("R100") carries two paths; the second is where the file
          // lives now, which is what every other caller here means by "path".
          const path = rest.at(-1) ?? "";
          const status =
            code === "A"
              ? ("added" as const)
              : code === "D"
                ? ("deleted" as const)
                : ("modified" as const);

          return { path, status };
        })
        .filter((entry) => entry.path !== "");
    } finally {
      await rm(dirname(scratchIndex), { recursive: true, force: true });
    }
  }

  /** A path's content in the fork's worktree at the revision it started from. */
  async readForkBaseFile(runId: string, path: string): Promise<string | null> {
    const handle = this.forks.get(runId);

    if (!handle) {
      throw new Error(`No such fork: ${runId}`);
    }

    try {
      return await this.git(handle.worktreePath, [
        "show",
        `${handle.fork.revision}:${path}`,
      ]);
    } catch {
      // Git's own reason ("path does not exist in <rev>", a bad revision, a
      // transient failure) is not distinguished here — every case means there
      // is nothing to compare against, which is what null already says to the
      // caller for "this file did not exist yet".
      return null;
    }
  }

  /** A path's current content in the fork's live working tree. */
  async readForkFile(runId: string, path: string): Promise<string | null> {
    const handle = this.forks.get(runId);

    if (!handle) {
      throw new Error(`No such fork: ${runId}`);
    }

    try {
      return await readFile(join(handle.worktreePath, path), "utf8");
    } catch {
      return null;
    }
  }

  private async applyBase(worktreePath: string, checkpoint: Checkpoint): Promise<void> {
    if (checkpoint.base.patch === null) {
      return;
    }

    // Written outside the worktree. A patch file inside it would be an
    // untracked file in the fork's own tree, and the fork's first `git status`
    // would show the human a file Novus left there.
    const scratch = await mkdtemp(join(tmpdir(), "novus-fork-"));
    const patchFile = join(scratch, "checkpoint.patch");

    try {
      await writeFile(patchFile, checkpoint.base.patch);
      await this.git(worktreePath, ["apply", "--whitespace=nowarn", patchFile]);
    } finally {
      await rm(scratch, { recursive: true, force: true });
    }
  }

  /**
   * Unmakes a worktree completely, or says why it could not.
   *
   * `git worktree remove` is tried first because it also clears the
   * administrative record under `.git/worktrees`. When it refuses — the
   * directory is already gone, the tree is dirty, the add died half-way — the
   * directory is removed directly and `prune` clears the record afterwards, so
   * a fork cannot survive as a registration pointing at nothing.
   */
  private async destroyWorktree(
    repositoryRoot: string,
    worktreePath: string,
    branch: string,
  ): Promise<void> {
    await this.git(repositoryRoot, ["worktree", "remove", "--force", worktreePath]).catch(
      () => "",
    );
    await rm(worktreePath, { recursive: true, force: true });
    await this.git(repositoryRoot, ["worktree", "prune"]).catch(() => "");
    await this.git(repositoryRoot, ["branch", "-D", branch]).catch(() => "");
  }

  private async resolveRepositoryRoot(): Promise<string> {
    if (this.repositoryRoot !== undefined) {
      return this.repositoryRoot;
    }

    const resolved = await realpath(resolve(this.repositoryPath)).catch(() => {
      throw new Error(`No such directory: ${this.repositoryPath}`);
    });

    this.repositoryRoot = resolved;

    return resolved;
  }

  /** The directory forks are created under, proven disjoint from the repository. */
  private async resolveForkRoot(repositoryRoot: string): Promise<string> {
    if (this.forkRoot !== undefined) {
      return this.forkRoot;
    }

    const requested = resolve(this.requestedForkRoot ?? defaultForkRoot(repositoryRoot));

    // Judged before it is created. Creating the directory first and refusing
    // afterwards would leave the refused directory sitting inside the human's
    // repository — a side effect from a call that reported failure.
    assertDisjoint(repositoryRoot, requested);

    await mkdir(requested, { recursive: true });

    // Again after resolution, because the answer can change: a symlinked path
    // is outside the repository as a string and inside it as a directory, and
    // the second reading is the one the filesystem will act on.
    const resolved = await realpath(requested);

    try {
      assertDisjoint(repositoryRoot, resolved);
    } catch (error) {
      await rmdir(requested).catch(() => undefined);
      throw error;
    }

    this.forkRoot = resolved;

    return resolved;
  }

  /**
   * Hands out development ports no other live fork holds.
   *
   * Reservation is what the isolation rule needs: two attempts must not be
   * given the same port. The free-port probe on top of that is a courtesy —
   * it skips ports something else is already listening on — and it cannot be
   * a guarantee, because anything may bind a port between this check and the
   * fork's dev server starting.
   */
  private async reservePorts(): Promise<number[]> {
    const allocated: number[] = [];

    for (
      let port = this.portBase;
      port < this.portBase + PORT_SCAN_LIMIT && allocated.length < this.portsPerFork;
      port += 1
    ) {
      if (this.reservedPorts.has(port)) {
        continue;
      }

      if (await isPortFree(port)) {
        this.reservedPorts.add(port);
        allocated.push(port);
      }
    }

    if (allocated.length < this.portsPerFork) {
      this.releasePorts(allocated);
      throw new Error(
        `No ${this.portsPerFork} free development ports in ${this.portBase}-${this.portBase + PORT_SCAN_LIMIT}.`,
      );
    }

    return allocated;
  }

  private releasePorts(ports: readonly number[]): void {
    for (const port of ports) {
      this.reservedPorts.delete(port);
    }
  }

  private async git(
    cwd: string,
    args: readonly string[],
    // Only ever GIT_INDEX_FILE, so a capture can stage into scratch space
    // instead of the parent's index. Merged over the inherited environment
    // rather than replacing it, because Git still needs the rest of it.
    environment?: Readonly<Record<string, string>>,
  ): Promise<string> {
    const { stdout } = await run("git", [...args], {
      cwd,
      timeout: GIT_TIMEOUT_MS,
      maxBuffer: GIT_MAX_BUFFER,
      ...(environment ? { env: { ...process.env, ...environment } } : {}),
    });

    return stdout;
  }
}

const exists = async (path: string): Promise<boolean> => {
  try {
    await stat(path);

    return true;
  } catch {
    return false;
  }
};

const messageOf = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

/**
 * The two events, as drafts the event store assigns identity and order to.
 *
 * Built here rather than emitted here. The manager touches Git and the
 * filesystem; making it also hold an event store would mean a fork could not
 * be created without one, and the sequence numbers that make these events
 * orderable are the store's to assign, not this class's to guess.
 */
export const checkpointCreatedEvent = (
  checkpoint: Checkpoint,
  actorId: string,
): SessionEventDraft => ({
  sessionId: checkpoint.sessionId,
  actorId,
  type: "checkpoint.created",
  payload: { checkpoint },
});

export const forkCreatedEvent = (fork: Fork, actorId: string): SessionEventDraft => ({
  sessionId: fork.sessionId,
  actorId,
  type: "fork.created",
  payload: { fork },
});
