import { execFile } from "node:child_process";
import { mkdir, mkdtemp, realpath, rm, rmdir, stat, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";

import {
  CheckpointSchema,
  ForkSchema,
  type Checkpoint,
  type Fork,
  type ModelSelection,
  type SessionEventDraft,
} from "@novus/contracts";

const run = promisify(execFile);

/**
 * Where a repository's forks live, given the repository.
 *
 * A sibling of the checkout, never a child of it. A worktree inside the
 * repository would appear in the parent's `git status`, in `list_directory`,
 * and in every search the parent agent runs — so the two attempts would be
 * reading each other's work through the one directory that is supposed to
 * separate them. One directory per repository keeps two projects' forks from
 * mixing, and `scripts/fleet.sh` puts its own worktrees in the same place for
 * the same reason.
 */
const defaultForkRoot = (repositoryRoot: string): string =>
  join(dirname(repositoryRoot), ".novus-forks", basename(repositoryRoot));

/**
 * The first development port a fork may be given.
 *
 * Above the host worker (4319) and both Vite servers (5273, 5274) so a fork's
 * dev server never lands on the port the human is already watching Novus on.
 */
const DEFAULT_PORT_BASE = 4400;
const DEFAULT_PORTS_PER_FORK = 2;
const PORT_SCAN_LIMIT = 512;

/** Git and filesystem calls are bounded: a fork must never hang the worker. */
const GIT_TIMEOUT_MS = 15_000;
const GIT_MAX_BUFFER = 64 * 1024 * 1024;

const isOutside = (root: string, target: string): boolean => {
  const fromRoot = relative(root, target);

  return fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot);
};

/**
 * Identifiers that become a path segment and a branch name.
 *
 * A run id is generated by Novus today, but a fork can also be asked for by a
 * client, and this is the point where "the fork's directory is derived from its
 * id" would otherwise become "the caller chooses any directory on the disk".
 * `../../etc` is a valid string and an invalid path segment, so the check is
 * on the character set rather than on what the resulting path looks like —
 * there is nothing to normalise away if nothing unusual was ever accepted.
 */
const SAFE_IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;

/**
 * Neither directory may contain the other.
 *
 * A fork root inside the repository would put every attempt's files in front
 * of the parent's own tools — `git status`, `list_directory`, every search.
 * A repository inside the fork root would mean tearing forks down could take
 * the human's checkout with it. Neither overlap "escapes" in the `..` sense,
 * which is why this is a containment check and not a path check.
 */
const assertDisjoint = (repositoryRoot: string, forkRoot: string): void => {
  if (!isOutside(repositoryRoot, forkRoot)) {
    throw new Error(
      `Fork worktrees must live outside the selected repository: ${forkRoot} is inside ${repositoryRoot}`,
    );
  }

  if (!isOutside(forkRoot, repositoryRoot)) {
    throw new Error(
      `The selected repository is inside the fork root: ${repositoryRoot} is inside ${forkRoot}`,
    );
  }
};

const assertSafeIdentifier = (value: string, what: string): void => {
  if (!SAFE_IDENTIFIER.test(value) || value.includes("..")) {
    throw new Error(
      `${what} must be letters, digits, dot, dash, or underscore: refused ${JSON.stringify(value)}`,
    );
  }
};

const isPortFree = (port: number): Promise<boolean> =>
  new Promise((settle) => {
    const server = createServer();

    server.once("error", () => settle(false));
    server.once("listening", () => {
      server.close(() => settle(true));
    });
    // Loopback only, like everything else Novus binds.
    server.listen(port, "127.0.0.1");
  });

export type CheckpointInput = {
  sessionId: string;
  parentRunId: string;
  /** The parent's event sequence this checkpoint covers. */
  parentSequence: number;
  agentState: string;
  goal: string;
  model: ModelSelection;
  toolPolicy: { allowWrites: boolean; allowCommands: boolean };
  contextManifest?: readonly string[] | undefined;
  constraints?: readonly string[] | undefined;
  budget?:
    | { remainingModelCalls: number | null; remainingTokens: number | null }
    | undefined;
};

export type ForkInput = {
  /** The fork's unique run id. Its worktree and branch are derived from it. */
  runId: string;
  label: string;
};

/**
 * A live fork: the record that goes in the log, plus what the host needs to
 * actually run in it.
 */
export type ForkHandle = {
  fork: Fork;
  worktreePath: string;
  branch: string;
  /**
   * The fork's process namespace, in the only form V1 can honestly provide.
   *
   * There are no containers in V1 and macOS has no cheap namespace primitive,
   * so a fork's separation from its sibling is: a different working directory,
   * different development ports, and an environment that names this fork
   * rather than inheriting the parent's. Anything spawned for this fork is
   * spawned with these, and nothing spawned for one fork can be handed the
   * other's repository path by accident.
   */
  environment: Record<string, string>;
};

/**
 * Creates and destroys the isolated checkouts that forked attempts run in.
 *
 * The unit of isolation is a Git worktree, because it is the only mechanism
 * here that is native, inspectable, and cheap: a second checkout of the same
 * object database, with its own working directory, index, and branch. Copying
 * the repository would be none of those things, and running two attempts in
 * one directory is what this class exists to make impossible.
 *
 * Every fork this manager makes is also every fork it will remove. A worktree
 * it did not create is not its business, and a creation that fails part-way is
 * unmade before the error is raised — `scripts/fleet.sh` learned that a
 * half-made worktree is worse than no worktree, because it looks usable right
 * up until an agent is standing in it.
 */
export class WorktreeManager {
  private readonly repositoryPath: string;
  private readonly requestedForkRoot: string | undefined;
  private readonly portBase: number;
  private readonly portsPerFork: number;
  private readonly forks = new Map<string, ForkHandle>();
  private readonly reservedPorts = new Set<number>();
  private repositoryRoot: string | undefined;
  private forkRoot: string | undefined;

  constructor(
    repositoryPath: string,
    options: {
      forkRoot?: string | undefined;
      portBase?: number | undefined;
      portsPerFork?: number | undefined;
    } = {},
  ) {
    this.repositoryPath = repositoryPath;
    this.requestedForkRoot = options.forkRoot;
    this.portBase = options.portBase ?? DEFAULT_PORT_BASE;
    this.portsPerFork = options.portsPerFork ?? DEFAULT_PORTS_PER_FORK;
  }

  list(): ForkHandle[] {
    return [...this.forks.values()];
  }

  get(runId: string): ForkHandle | undefined {
    return this.forks.get(runId);
  }

  /**
   * Captures the state a fork can be started from.
   *
   * Reads the repository and writes nothing to it. That is not an efficiency
   * argument: checkpointing is something a human does *while* a run is going,
   * and a capture that staged files or wrote a stash would change the tree the
   * parent run is still working in.
   *
   * The patch covers tracked modifications only. A file the agent created but
   * never added is not in `git diff HEAD` and will not exist in the fork —
   * including it would mean running `git add -N` against the parent's index,
   * which is exactly the mutation the paragraph above refuses. Callers that
   * need untracked work carried across must commit it first.
   */
  async createCheckpoint(input: CheckpointInput): Promise<Checkpoint> {
    const repositoryRoot = await this.resolveRepositoryRoot();

    const revision = await this.git(repositoryRoot, ["rev-parse", "HEAD"])
      .then((stdout) => stdout.trim())
      .catch(() => "");

    if (revision.length === 0) {
      // Not a soft failure with a null revision, the way a receipt reports one.
      // A fork has to check something out, and there is nothing here to check
      // out — saying so now is better than a worktree add that fails later
      // with Git's own wording.
      throw new Error(
        `Cannot checkpoint ${repositoryRoot}: it is not a Git repository with a commit to fork from.`,
      );
    }

    // --binary so a checkpoint of a tree containing changed binary files still
    // reproduces, rather than applying cleanly and quietly dropping them.
    const patch = await this.git(repositoryRoot, ["diff", "--binary", "HEAD"]).catch(
      () => "",
    );

    return CheckpointSchema.parse({
      id: crypto.randomUUID(),
      sessionId: input.sessionId,
      parentRunId: input.parentRunId,
      parentSequence: input.parentSequence,
      base: {
        revision,
        patch: patch.length > 0 ? patch : null,
      },
      agentState: input.agentState,
      contextManifest: [...(input.contextManifest ?? [])],
      goal: input.goal,
      constraints: [...(input.constraints ?? [])],
      model: input.model,
      toolPolicy: input.toolPolicy,
      budget: input.budget ?? {
        remainingModelCalls: null,
        remainingTokens: null,
      },
      createdAt: new Date().toISOString(),
    });
  }

  /**
   * Materialises a checkpoint as its own checkout on its own branch.
   *
   * Ordered so that the cheap refusals happen before anything exists on disk:
   * a bad identifier, a fork root that overlaps the repository, or a directory
   * already in the way all fail with nothing to undo. Only once the ports are
   * reserved and the path is proven to be inside the fork root does Git get
   * asked to create anything — and from that line on, every failure path runs
   * the same teardown the caller would get from `removeFork`.
   */
  async createFork(checkpoint: Checkpoint, input: ForkInput): Promise<ForkHandle> {
    const validated = CheckpointSchema.parse(checkpoint);

    assertSafeIdentifier(input.runId, "A fork's run id");

    if (this.forks.has(input.runId)) {
      throw new Error(`Fork ${input.runId} already exists.`);
    }

    const repositoryRoot = await this.resolveRepositoryRoot();
    const forkRoot = await this.resolveForkRoot(repositoryRoot);
    const worktreePath = join(forkRoot, input.runId);
    const branch = `novus/fork/${input.runId}`;

    // The identifier check should already make this impossible. It is asserted
    // anyway because it is the actual invariant — "no fork escapes its root" —
    // and an invariant that is only enforced by a regular expression somewhere
    // else is one edit away from not being enforced at all.
    if (isOutside(forkRoot, worktreePath) || worktreePath === forkRoot) {
      throw new Error(
        `A fork's worktree must live under ${forkRoot}: refused ${worktreePath}`,
      );
    }

    if (await exists(worktreePath)) {
      throw new Error(`${worktreePath} already exists — refusing to fork onto it.`);
    }

    const devPorts = await this.reservePorts();

    try {
      await this.git(repositoryRoot, [
        "worktree",
        "add",
        "--no-track",
        "-b",
        branch,
        worktreePath,
        validated.base.revision,
      ]);
    } catch (error) {
      this.releasePorts(devPorts);
      throw new Error(
        `Could not create a worktree for fork ${input.runId}: ${messageOf(error)}`,
      );
    }

    try {
      await this.applyBase(worktreePath, validated);

      const fork = ForkSchema.parse({
        runId: input.runId,
        sessionId: validated.sessionId,
        checkpointId: validated.id,
        parentRunId: validated.parentRunId,
        label: input.label,
        worktreePath: await realpath(worktreePath),
        branch,
        revision: validated.base.revision,
        devPorts,
        createdAt: new Date().toISOString(),
      });

      const handle: ForkHandle = {
        fork,
        worktreePath: fork.worktreePath,
        branch,
        environment: {
          NOVUS_REPO: fork.worktreePath,
          NOVUS_SESSION: fork.sessionId,
          NOVUS_RUN: fork.runId,
          NOVUS_FORK_PORTS: devPorts.join(","),
          PORT: String(devPorts[0]),
        },
      };

      this.forks.set(fork.runId, handle);

      return handle;
    } catch (error) {
      // The worktree exists and is wrong. Leaving it would hand the next
      // caller a checkout that is missing the parent's uncommitted work while
      // looking, from the outside, exactly like a good one.
      await this.destroyWorktree(repositoryRoot, worktreePath, branch);
      this.releasePorts(devPorts);

      throw new Error(
        `Could not start fork ${input.runId} from checkpoint ${validated.id}: ${messageOf(error)}`,
      );
    }
  }

  /**
   * Removes a fork's checkout and the branch that only it was using.
   *
   * The branch goes with the worktree deliberately. A fork's branch is not a
   * place work is kept — the selected attempt is applied as a patch, which is
   * Milestone 4's `apply selected patch` step — so leaving it behind would
   * accumulate one dead branch per attempt in the human's own repository.
   */
  async removeFork(runId: string): Promise<void> {
    const handle = this.forks.get(runId);

    if (!handle) {
      throw new Error(`No such fork: ${runId}`);
    }

    const repositoryRoot = await this.resolveRepositoryRoot();

    await this.destroyWorktree(repositoryRoot, handle.worktreePath, handle.branch);
    this.releasePorts(handle.fork.devPorts);
    this.forks.delete(runId);
  }

  /** Tears down every fork this manager still owns, reporting the first failure. */
  async removeAll(): Promise<void> {
    const failures: string[] = [];

    for (const runId of [...this.forks.keys()]) {
      try {
        await this.removeFork(runId);
      } catch (error) {
        failures.push(`${runId}: ${messageOf(error)}`);
      }
    }

    if (failures.length > 0) {
      throw new Error(`Some forks could not be removed — ${failures.join("; ")}`);
    }
  }

  private async applyBase(worktreePath: string, checkpoint: Checkpoint): Promise<void> {
    if (checkpoint.base.patch === null) {
      return;
    }

    // Written outside the worktree. A patch file inside it would be an
    // untracked file in the fork's own tree, and the fork's first `git status`
    // would show the human a file Novus left there.
    const scratch = await mkdtemp(join(tmpdir(), "novus-fork-"));
    const patchFile = join(scratch, "checkpoint.patch");

    try {
      await writeFile(patchFile, checkpoint.base.patch);
      await this.git(worktreePath, ["apply", "--whitespace=nowarn", patchFile]);
    } finally {
      await rm(scratch, { recursive: true, force: true });
    }
  }

  /**
   * Unmakes a worktree completely, or says why it could not.
   *
   * `git worktree remove` is tried first because it also clears the
   * administrative record under `.git/worktrees`. When it refuses — the
   * directory is already gone, the tree is dirty, the add died half-way — the
   * directory is removed directly and `prune` clears the record afterwards, so
   * a fork cannot survive as a registration pointing at nothing.
   */
  private async destroyWorktree(
    repositoryRoot: string,
    worktreePath: string,
    branch: string,
  ): Promise<void> {
    await this.git(repositoryRoot, ["worktree", "remove", "--force", worktreePath]).catch(
      () => "",
    );
    await rm(worktreePath, { recursive: true, force: true });
    await this.git(repositoryRoot, ["worktree", "prune"]).catch(() => "");
    await this.git(repositoryRoot, ["branch", "-D", branch]).catch(() => "");
  }

  private async resolveRepositoryRoot(): Promise<string> {
    if (this.repositoryRoot !== undefined) {
      return this.repositoryRoot;
    }

    const resolved = await realpath(resolve(this.repositoryPath)).catch(() => {
      throw new Error(`No such directory: ${this.repositoryPath}`);
    });

    this.repositoryRoot = resolved;

    return resolved;
  }

  /** The directory forks are created under, proven disjoint from the repository. */
  private async resolveForkRoot(repositoryRoot: string): Promise<string> {
    if (this.forkRoot !== undefined) {
      return this.forkRoot;
    }

    const requested = resolve(this.requestedForkRoot ?? defaultForkRoot(repositoryRoot));

    // Judged before it is created. Creating the directory first and refusing
    // afterwards would leave the refused directory sitting inside the human's
    // repository — a side effect from a call that reported failure.
    assertDisjoint(repositoryRoot, requested);

    await mkdir(requested, { recursive: true });

    // Again after resolution, because the answer can change: a symlinked path
    // is outside the repository as a string and inside it as a directory, and
    // the second reading is the one the filesystem will act on.
    const resolved = await realpath(requested);

    try {
      assertDisjoint(repositoryRoot, resolved);
    } catch (error) {
      await rmdir(requested).catch(() => undefined);
      throw error;
    }

    this.forkRoot = resolved;

    return resolved;
  }

  /**
   * Hands out development ports no other live fork holds.
   *
   * Reservation is what the isolation rule needs: two attempts must not be
   * given the same port. The free-port probe on top of that is a courtesy —
   * it skips ports something else is already listening on — and it cannot be
   * a guarantee, because anything may bind a port between this check and the
   * fork's dev server starting.
   */
  private async reservePorts(): Promise<number[]> {
    const allocated: number[] = [];

    for (
      let port = this.portBase;
      port < this.portBase + PORT_SCAN_LIMIT && allocated.length < this.portsPerFork;
      port += 1
    ) {
      if (this.reservedPorts.has(port)) {
        continue;
      }

      if (await isPortFree(port)) {
        this.reservedPorts.add(port);
        allocated.push(port);
      }
    }

    if (allocated.length < this.portsPerFork) {
      this.releasePorts(allocated);
      throw new Error(
        `No ${this.portsPerFork} free development ports in ${this.portBase}-${this.portBase + PORT_SCAN_LIMIT}.`,
      );
    }

    return allocated;
  }

  private releasePorts(ports: readonly number[]): void {
    for (const port of ports) {
      this.reservedPorts.delete(port);
    }
  }

  private async git(cwd: string, args: readonly string[]): Promise<string> {
    const { stdout } = await run("git", [...args], {
      cwd,
      timeout: GIT_TIMEOUT_MS,
      maxBuffer: GIT_MAX_BUFFER,
    });

    return stdout;
  }
}

const exists = async (path: string): Promise<boolean> => {
  try {
    await stat(path);

    return true;
  } catch {
    return false;
  }
};

const messageOf = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

/**
 * The two events, as drafts the event store assigns identity and order to.
 *
 * Built here rather than emitted here. The manager touches Git and the
 * filesystem; making it also hold an event store would mean a fork could not
 * be created without one, and the sequence numbers that make these events
 * orderable are the store's to assign, not this class's to guess.
 */
export const checkpointCreatedEvent = (
  checkpoint: Checkpoint,
  actorId: string,
): SessionEventDraft => ({
  sessionId: checkpoint.sessionId,
  actorId,
  type: "checkpoint.created",
  payload: { checkpoint },
});

export const forkCreatedEvent = (fork: Fork, actorId: string): SessionEventDraft => ({
  sessionId: fork.sessionId,
  actorId,
  type: "fork.created",
  payload: { fork },
});
